CREATE SCHEMA Venta; --SE CREA EL ESQUEMA DE VENTAS CON LA TABLA PRINCIPAL DE DATOS DE CLIENTE Y FECHA DE REGISTRO--
	CREATE TABLE Venta.Clientes (
	IDCliente INT PRIMARY KEY,
	Nombre VARCHAR(100),
	Fecha_Registro DATE
);
CREATE SCHEMA Logistica;--SE CREA EL ESQUEMA DE LOGISTICA CON DOS TABLAS: PRODUCTOS POR LA NECESIDAD DE VER LOS PROD Y EL STOCK
	CREATE TABLE Logistica.Productos (
	IDProducto INT PRIMARY KEY, 
	Nombre VARCHAR(100),
	Stock INT
	);
	CREATE TABLE Logistica.Envios ( --SE CREA TABLA DE ENVIOS PARA TENER INFORMACION DE DESTINO Y FECHAS
	IDEnvio INT PRIMARY KEY,
	Destino VARCHAR (100),
	FechaEnvio DATE
	);
CREATE SCHEMA Analisis; --SE CREA ESQUEMA DE ANALISIS: TABLA ANALISIS RESUMENMES PARA CONSOLIDAR LA INFORMACION DE VENTAS DEL MES
	CREATE TABLE Analisis.ResumenMes (
	IDresumen INT PRIMARY KEY,
	Mes VARCHAR(20),
	TotalPedidos INT,
	TotalClientes INT,
	TotalIngresos DECIMAL(10,2)
	);
	CREATE TABLE Analisis.IndicadoresVentas( --TABLA QUE INDICA VENTAS TOTALES POR MES/PEDIDO QUE AYUDA A LA TOMA DE DECISIONES SEGUN SUS VENTAS--
	IDIndicador INT PRIMARY KEY,
	Mes VARCHAR(100),
	TotalVentas DECIMAL (10,2),
	CantidadPedidos INT
	);

